INSERT INTO movies (movie_name) VALUES
    ('The Shawshank Redemption'),
    ('The Godfather'),
    ('The Dark Knight'),
    ('Pulp Fiction'),
    ('The Lord of the Rings: The Return of the King'),
    ('Forrest Gump'),
    ('Inception'),
    ('The Matrix'),
    ('The Avengers'),
    ('Jurassic Park'),
    ('Star Wars: Episode IV - A New Hope'),
    ('Avatar'),
    ('Titanic'),
    ('Toy Story'),
    ('Finding Nemo'),
    ('The Lion King'),
    ('Braveheart'),
    ('Gladiator'),
    ('Interstellar'),
    ('The Social Network'),
    ('The Wolf of Wall Street'),
    ('The Grand Budapest Hotel'),
    ('Guardians of the Galaxy'),
    ('Deadpool'),
    ('Mad Max: Fury Road'),
    ('La La Land'),
    ('Inglourious Basterds'),
    ('The Revenant'),
    ('Django Unchained'),
    ('The Departed');

INSERT INTO reviews (movie_id, review) VALUES
    (1, 'An absolute classic.'),
    (2, 'A masterpiece.'),
    (3, 'One of the best superhero movies.'),
    (4, 'Quentin Tarantino at his finest.'),
    (5, 'Epic conclusion to the trilogy.'),
    (6, 'Heartwarming and inspirational.'),
    (7, 'Mind-bending story with stunning visuals.'),
    (8, 'Revolutionized action films.'),
    (9, 'A superhero ensemble done right.'),
    (10, 'Dinosaurs brought back to life.'),
    (11, 'A sci-fi legend.'),
    (12, 'Visually groundbreaking.'),
    (13, 'A tearjerker.'),
    (14, 'Revolutionized animation.'),
    (15, 'Charming and unforgettable.'),
    (16, 'A historical epic.'),
    (17, 'Intense and powerful.'),
    (18, 'Gladiatorial combat at its best.'),
    (19, 'Astounding space odyssey.'),
    (20, 'Captivating portrayal of Facebook.'),
    (21, 'Wild and excessive.'),
    (22, 'Quirky and delightful.'),
    (23, 'Hilarious and irreverent.'),
    (24, 'Visually stunning post-apocalypse.'),
    (25, 'Musical masterpiece.'),
    (26, 'Tarantino''s unique take on WWII.'),
    (27, 'Gritty and visually striking.'),
    (28, 'Raw and intense survival story.'),
    (29, 'Inventive and action-packed.'),
    (30, 'Gritty crime drama.');